import React, { useState, useEffect, useRef } from 'react';
import {
  View,
  Text,
  StyleSheet,
  TouchableOpacity,
  ActivityIndicator,
  Alert,
  Dimensions,
  ScrollView,
  Platform,
} from 'react-native';
import { useRouter, useLocalSearchParams } from 'expo-router';
import { CameraView, useCameraPermissions } from 'expo-camera';
import { Ionicons } from '@expo/vector-icons';
import { supabase } from '@/lib/supabase';
import { CreovatorTheme } from '@/constants/theme';
import { CreovatorHeader, CreovatorInput, CreovatorButton, CreovatorCard } from '@/components/creovator';

const { width } = Dimensions.get('window');

interface QrPayload {
  participantId: string;
  eventId: string;
}

interface ParticipantDetail {
  id: string;
  name: string;
  email?: string;
  phone?: string;
  organization?: string;
  category?: string;
  list_name?: string;
}

type ScanStatus = 'idle' | 'scanning' | 'success' | 'already' | 'error';

export default function QrScanScreen() {
  const router = useRouter();
  const searchParams = useLocalSearchParams();
  const preselectedEventId = searchParams.event_id as string;

  const [permission, requestPermission] = useCameraPermissions();
  const [cameraActive, setCameraActive] = useState(true);
  const [scannedData, setScannedData] = useState('');
  const [manualCode, setManualCode] = useState('');
  const [status, setStatus] = useState<ScanStatus>('idle');
  const [loading, setLoading] = useState(false);
  const [participant, setParticipant] = useState<ParticipantDetail | null>(null);
  const [eventName, setEventName] = useState('');
  const [checkedInAt, setCheckedInAt] = useState('');
  const [statusMessage, setStatusMessage] = useState('');

  const parseQrPayload = (raw: string): QrPayload | null => {
    try {
      // 1. Check if valid JSON format
      const parsed = JSON.parse(raw);
      if (parsed.participantId && parsed.eventId) return parsed;
    } catch {
      // 2. Fallback to colon-separated format
      const parts = raw.split(':');
      if (parts[0] === 'creavator' || parts[0] === 'creovator' && parts.length >= 3) {
        return { participantId: parts[1], eventId: parts[2] };
      }
    }
    return null;
  };

  const processCheckIn = async (rawString: string) => {
    const trimmed = rawString.trim();
    if (!trimmed) return;

    setLoading(true);
    setStatus('scanning');

    try {
      const payload = parseQrPayload(trimmed);
      if (!payload) {
        setStatus('error');
        setStatusMessage('Invalid QR code format. Ensure it was generated by Creovator.');
        setLoading(false);
        return;
      }

      // 1. Fetch Event Name
      const { data: ev } = await supabase
        .from('events')
        .select('name')
        .eq('id', payload.eventId)
        .maybeSingle();

      if (ev) setEventName(ev.name);

      // 2. Fetch Participant Details
      const { data: pData, error: pErr } = await supabase
        .from('participants')
        .select('*')
        .eq('id', payload.participantId)
        .maybeSingle();

      if (pErr || !pData) {
        setStatus('error');
        setStatusMessage('Attendee record not found in the database.');
        setLoading(false);
        return;
      }

      setParticipant(pData);

      // 3. Check previous attendance
      const { data: existingAtt } = await supabase
        .from('attendance')
        .select('*')
        .eq('participant_id', payload.participantId)
        .eq('event_id', payload.eventId)
        .maybeSingle();

      if (existingAtt) {
        setStatus('already');
        setCheckedInAt(
          new Date(existingAtt.checked_in_at || existingAtt.created_at).toLocaleTimeString([], {
            hour: '2-digit',
            minute: '2-digit',
          })
        );
        setStatusMessage(`Already checked in today at ${existingAtt.checked_in_at || 'earlier'}`);
        setLoading(false);
        return;
      }

      // 4. Record new attendance check-in
      const nowStr = new Date().toISOString();
      const { error: attErr } = await supabase.from('attendance').insert([
        {
          participant_id: payload.participantId,
          event_id: payload.eventId,
          checked_in_at: nowStr,
        },
      ]);

      if (attErr) throw attErr;

      setStatus('success');
      setCheckedInAt(new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }));
      setStatusMessage('Check-in verified successfully!');
    } catch (err: any) {
      setStatus('error');
      setStatusMessage(err.message || 'Check-in failed.');
    } finally {
      setLoading(false);
    }
  };

  const handleBarcodeScanned = ({ data }: { data: string }) => {
    if (loading || status === 'success') return;
    setScannedData(data);
    setCameraActive(false);
    processCheckIn(data);
  };

  const handleManualSubmit = () => {
    if (!manualCode.trim()) {
      Alert.alert('Empty Code', 'Please enter the participant or QR payload string.');
      return;
    }
    processCheckIn(manualCode.trim());
  };

  const resetScan = () => {
    setStatus('idle');
    setParticipant(null);
    setScannedData('');
    setManualCode('');
    setStatusMessage('');
    setCameraActive(true);
  };

  return (
    <View style={styles.container}>
      <CreovatorHeader
        title="Live QR Scanner"
        subtitle={eventName || 'Entry & Attendance Check-in'}
        showBack
      />

      <ScrollView contentContainerStyle={styles.scrollContent} showsVerticalScrollIndicator={false}>
        {/* Camera Viewport or Verification State */}
        {cameraActive && status === 'idle' ? (
          <View style={styles.cameraCard}>
            {!permission ? (
              <View style={styles.permNotice}>
                <ActivityIndicator color={CreovatorTheme.colors.primary} />
                <Text style={styles.permText}>Requesting camera permission...</Text>
              </View>
            ) : !permission.granted ? (
              <View style={styles.permNotice}>
                <Ionicons name="camera-outline" size={48} color={CreovatorTheme.colors.textMuted} />
                <Text style={styles.permTitle}>Camera Access Required</Text>
                <Text style={styles.permDesc}>
                  Please grant camera permission to scan participant QR badges live.
                </Text>
                <CreovatorButton
                  title="Grant Permission"
                  onPress={requestPermission}
                  size="sm"
                  style={{ marginTop: 12 }}
                />
              </View>
            ) : (
              <View style={styles.cameraWrap}>
                <CameraView
                  style={StyleSheet.absoluteFillObject}
                  facing="back"
                  barcodeScannerSettings={{
                    barcodeTypes: ['qr'],
                  }}
                  onBarcodeScanned={handleBarcodeScanned}
                />
                {/* Viewfinder Target Frame */}
                <View style={styles.viewfinderOverlay}>
                  <View style={styles.targetFrame}>
                    <View style={[styles.targetCorner, styles.tTL]} />
                    <View style={[styles.targetCorner, styles.tTR]} />
                    <View style={[styles.targetCorner, styles.tBL]} />
                    <View style={[styles.targetCorner, styles.tBR]} />
                  </View>
                  <Text style={styles.targetInstructions}>Align QR code inside frame</Text>
                </View>
              </View>
            )}
          </View>
        ) : null}

        {/* Verification Result Card */}
        {status !== 'idle' && (
          <CreovatorCard
            style={[
              styles.resultCard,
              status === 'success' ? styles.cardSuccess : undefined,
              status === 'already' ? styles.cardAlready : undefined,
              status === 'error' ? styles.cardError : undefined,
            ]}
          >
            <View style={styles.resultHeader}>
              <View
                style={[
                  styles.resultIconCircle,
                  status === 'success' && { backgroundColor: 'rgba(16, 185, 129, 0.2)' },
                  status === 'already' && { backgroundColor: 'rgba(249, 187, 30, 0.2)' },
                  status === 'error' && { backgroundColor: 'rgba(239, 68, 68, 0.2)' },
                ]}
              >
                <Ionicons
                  name={
                    status === 'success'
                      ? 'checkmark-circle'
                      : status === 'already'
                      ? 'time'
                      : 'alert-circle'
                  }
                  size={36}
                  color={
                    status === 'success'
                      ? CreovatorTheme.colors.success
                      : status === 'already'
                      ? CreovatorTheme.colors.secondary
                      : CreovatorTheme.colors.destructive
                  }
                />
              </View>

              <Text style={styles.resultStatusTitle}>
                {status === 'success'
                  ? 'CHECK-IN VERIFIED'
                  : status === 'already'
                  ? 'ALREADY CHECKED IN'
                  : 'VERIFICATION FAILED'}
              </Text>
              <Text style={styles.resultStatusSub}>{statusMessage}</Text>
            </View>

            {participant && (
              <View style={styles.attendeeDetailsBox}>
                <View style={styles.detailItem}>
                  <Text style={styles.detailLabel}>Attendee Name</Text>
                  <Text style={styles.detailValue}>{participant.name}</Text>
                </View>

                {participant.category || participant.list_name ? (
                  <View style={styles.detailItem}>
                    <Text style={styles.detailLabel}>Role / Category</Text>
                    <Text style={[styles.detailValue, { color: CreovatorTheme.colors.primary }]}>
                      {participant.category || participant.list_name}
                    </Text>
                  </View>
                ) : null}

                {participant.organization ? (
                  <View style={styles.detailItem}>
                    <Text style={styles.detailLabel}>Organization</Text>
                    <Text style={styles.detailValue}>{participant.organization}</Text>
                  </View>
                ) : null}

                {eventName ? (
                  <View style={styles.detailItem}>
                    <Text style={styles.detailLabel}>Event</Text>
                    <Text style={styles.detailValue}>{eventName}</Text>
                  </View>
                ) : null}

                {checkedInAt ? (
                  <View style={styles.detailItem}>
                    <Text style={styles.detailLabel}>Time</Text>
                    <Text style={styles.detailValue}>{checkedInAt}</Text>
                  </View>
                ) : null}
              </View>
            )}

            <CreovatorButton
              title="Scan Next Attendee"
              onPress={resetScan}
              size="lg"
              icon={<Ionicons name="scan" size={20} color="#ffffff" />}
              style={{ marginTop: 16 }}
            />
          </CreovatorCard>
        )}

        {/* Fallback Manual Entry Strip */}
        <CreovatorCard style={styles.manualEntryCard}>
          <Text style={styles.manualTitle}>Manual Code Entry</Text>
          <Text style={styles.manualDesc}>
            Type or paste the attendee verification code / ID if camera is unavailable:
          </Text>

          <CreovatorInput
            placeholder='Paste JSON or format "creovator:id:event"'
            value={manualCode}
            onChangeText={setManualCode}
            leftIcon={<Ionicons name="key-outline" size={16} color={CreovatorTheme.colors.textMuted} />}
          />

          <CreovatorButton
            title="Verify & Check In"
            variant="secondary"
            onPress={handleManualSubmit}
            loading={loading && status === 'scanning'}
            icon={<Ionicons name="checkmark-done" size={18} color="#0f0a1f" />}
          />
        </CreovatorCard>
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: CreovatorTheme.colors.bgDark,
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 40,
  },
  cameraCard: {
    height: 340,
    backgroundColor: '#000000',
    borderRadius: 24,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: CreovatorTheme.colors.cardBorder,
    marginBottom: 16,
  },
  cameraWrap: {
    flex: 1,
    position: 'relative',
  },
  viewfinderOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0, 0, 0, 0.45)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  targetFrame: {
    width: 220,
    height: 220,
    position: 'relative',
    backgroundColor: 'transparent',
  },
  targetCorner: {
    position: 'absolute',
    width: 28,
    height: 28,
    borderColor: CreovatorTheme.colors.cyan,
  },
  tTL: {
    top: 0,
    left: 0,
    borderTopWidth: 3,
    borderLeftWidth: 3,
  },
  tTR: {
    top: 0,
    right: 0,
    borderTopWidth: 3,
    borderRightWidth: 3,
  },
  tBL: {
    bottom: 0,
    left: 0,
    borderBottomWidth: 3,
    borderLeftWidth: 3,
  },
  tBR: {
    bottom: 0,
    right: 0,
    borderBottomWidth: 3,
    borderRightWidth: 3,
  },
  targetInstructions: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '700',
    marginTop: 20,
    letterSpacing: 0.5,
  },
  permNotice: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  permText: {
    fontSize: 13,
    color: CreovatorTheme.colors.textMuted,
    marginTop: 8,
  },
  permTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: CreovatorTheme.colors.textWhite,
    marginTop: 12,
  },
  permDesc: {
    fontSize: 13,
    color: CreovatorTheme.colors.textMuted,
    textAlign: 'center',
    marginTop: 6,
    lineHeight: 18,
  },
  resultCard: {
    padding: 22,
    marginBottom: 16,
  },
  cardSuccess: {
    borderColor: CreovatorTheme.colors.success,
  },
  cardAlready: {
    borderColor: CreovatorTheme.colors.secondary,
  },
  cardError: {
    borderColor: CreovatorTheme.colors.destructive,
  },
  resultHeader: {
    alignItems: 'center',
    marginBottom: 16,
  },
  resultIconCircle: {
    width: 68,
    height: 68,
    borderRadius: 34,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
  },
  resultStatusTitle: {
    fontSize: 20,
    fontWeight: '900',
    color: CreovatorTheme.colors.textWhite,
  },
  resultStatusSub: {
    fontSize: 13,
    color: CreovatorTheme.colors.textMuted,
    textAlign: 'center',
    marginTop: 4,
  },
  attendeeDetailsBox: {
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 16,
    padding: 16,
    gap: 10,
  },
  detailItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  detailLabel: {
    fontSize: 12,
    color: CreovatorTheme.colors.textMuted,
    fontWeight: '600',
  },
  detailValue: {
    fontSize: 14,
    fontWeight: '800',
    color: CreovatorTheme.colors.textWhite,
  },
  manualEntryCard: {
    padding: 18,
  },
  manualTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: CreovatorTheme.colors.textWhite,
    marginBottom: 4,
  },
  manualDesc: {
    fontSize: 12,
    color: CreovatorTheme.colors.textMuted,
    lineHeight: 16,
    marginBottom: 12,
  },
});
